using Content.Client.Pinpointer.UI;
using Content.Shared._Starlight.Holograms;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._Starlight.Holograms.UI;

[GenerateTypedNameReferences]
public sealed partial class HologramConsoleWindow : BaseWindow
{
    private readonly IEntityManager _entManager;
    private readonly SpriteSystem _spriteSystem;

    private NetEntity? _selectedBladeServer;
    private NetEntity? _selectedProjector;
    private bool _isPortableMode;
    private readonly Texture? _blipTexture;
    private HologramConsoleBoundUserInterfaceState? _currentState;

    public event Action<NetEntity, NetEntity>? OnProjectHologram;
    public event Action? OnRecallHologram;
    public event Action<NetEntity>? OnEjectBladeServer;
    public event Action<bool>? OnToggleCarry;

    public HologramConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();
        _spriteSystem = _entManager.System<SpriteSystem>();

        _blipTexture = _spriteSystem.Frame0(
            new SpriteSpecifier.Texture(
                new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));

        NavMap.Visible = false;
        NoServerOverlay.Visible = true;

        ProjectButton.OnPressed += _ =>
        {
            if (_selectedBladeServer.HasValue)
            {
                var projector = _isPortableMode
                    ? NetEntity.Invalid
                    : (_selectedProjector ?? NetEntity.Invalid);

                OnProjectHologram?.Invoke(_selectedBladeServer.Value, projector);
            }
        };

        RecallButton.OnPressed += _ => OnRecallHologram?.Invoke();
        AllowCarryCheckbox.OnToggled += args => OnToggleCarry?.Invoke(args.Pressed);

        NavMap.TrackedEntitySelectedAction += OnProjectorSelectedFromMap;
    }

    private void OnProjectorSelectedFromMap(NetEntity? netEntity)
    {
        if (!netEntity.HasValue)
            return;

        _selectedProjector = netEntity.Value;
        UpdateSelectionStateAfterChange();
    }

    private void SetupNavMap(HologramConsoleBoundUserInterfaceState state)
    {
        if (_blipTexture == null || state.ProjectorCoordinates.Count == 0)
            return;

        NavMap.Visible = true;

        var firstCoords = _entManager.GetCoordinates(
            state.ProjectorCoordinates.Values.First());

        if (_entManager.TryGetComponent(firstCoords.EntityId, out TransformComponent? xform))
            NavMap.MapUid = xform.GridUid;

        UpdateNavMapBlips(state);
        NavMap.ForceNavMapUpdate();
    }

    private void UpdateNavMapBlips(HologramConsoleBoundUserInterfaceState state)
    {
        if (_blipTexture == null)
            return;

        NavMap.TrackedEntities.Clear();

        foreach (var (netEntity, netCoords) in state.ProjectorCoordinates)
        {
            var coords = _entManager.GetCoordinates(netCoords);
            var selected = netEntity == _selectedProjector;
            var color = NavMap.GetProjectorColor(selected);

            NavMap.TrackedEntities[netEntity] =
                new NavMapBlip(coords, _blipTexture, color, true, true);
        }
    }

    private void UpdateSelectionStateAfterChange()
    {
        if (_currentState == null)
            return;

        UpdateSelectionState(_currentState);
        UpdateNavMapBlips(_currentState);
    }

    public void UpdateState(HologramConsoleBoundUserInterfaceState state)
    {
        _currentState = state;
        _isPortableMode = state.IsPortable;

        // --- Visibility toggles ---
        BatteryPanel.Visible = state.IsPortable;
        SettingsPanel.Visible = state.IsPortable;
        ModeLabel.Visible = state.IsPortable;

        MapPanel.Visible = state.ShowMap;
        LeftPanel.Visible = state.ShowBladeServerPanel;
        ProjectButton.Visible = state.ShowProjectButton;
        RecallButton.Visible = state.ShowRecallButton;
        ControlsPanel.Visible = state.ShowProjectButton || state.ShowRecallButton;

        // Portable Mode
        if (state.IsPortable)
        {
            ModeLabel.Text = "PORTABLE MODE";

            NavMap.Visible = false;
            NoServerOverlay.Visible = false;

            UpdateBattery(state);

            AllowCarryCheckbox.Pressed = state.AllowCarry;

            PortableInfoLabel.Visible = true;
            PortableInfoLabel.Text = $"Active: {state.ActiveCount} / {state.MaxActive}";
        }
        // Stationary Mode
        else
        {
            PortableInfoLabel.Visible = false;

            if (!state.HasServer)
            {
                HandleNoServerState();
                return;
            }

            NoBladeServersLabel.Visible = false;
            NoServerOverlay.Visible = false;

            SetupNavMap(state);
        }

        // Common UI update
        UpdateBladeServerList(state);
        UpdateStatus(state);

        ProjectorCountLabel.Text =
            state.Projectors.Count > 0
                ? $" {state.Projectors.Count} Projectors "
                : " No Projectors ";

        if (!state.IsPortable && state.Projectors.Count == 0)
            ProjectButton.Disabled = true;

        UpdateSelectionState(state);
    }

    private void HandleNoServerState()
    {
        NoBladeServersLabel.Visible = true;
        NoServerOverlay.Visible = true;
        NavMap.Visible = false;

        BladeServersList.RemoveAllChildren();

        StatusLabel.Text = "No server connected";
        StatusLabel.FontColorOverride = Color.FromHex("#ef4444");

        ActiveIndicator.Text = "● OFFLINE";
        ActiveIndicator.FontColorOverride = Color.FromHex("#ef4444");

        ProjectButton.Disabled = true;
        RecallButton.Disabled = true;

        ProjectorCountLabel.Text = " No Projectors ";
    }

    private void UpdateBattery(HologramConsoleBoundUserInterfaceState state)
    {
        if (!state.BatteryPercent.HasValue)
            return;

        var percent = state.BatteryPercent.Value;

        BatteryBar.Value = Math.Clamp(percent / 100f, 0f, 1f);
        BatteryLabel.Text = $"{percent:F0}%";

        var color = percent switch
        {
            > 50 => "#10b981",
            > 20 => "#fbbf24",
            _ => "#ef4444"
        };

        BatteryLabel.FontColorOverride = Color.FromHex(color);
        BatteryBar.ForegroundStyleBoxOverride =
            new StyleBoxFlat { BackgroundColor = Color.FromHex(color) };
    }

    private void UpdateBladeServerList(HologramConsoleBoundUserInterfaceState state)
    {
        BladeServersList.RemoveAllChildren();

        if (state.BladeServers.Count == 0)
        {
            NoBladeServersLabel.Visible = true;
            return;
        }

        NoBladeServersLabel.Visible = false;

        var hasActive = state.ActiveHologram != null || state.ActiveCount > 0;

        foreach (var blade in state.BladeServers)
        {
            var entry = new BladeServerListEntry(blade, hasActive && blade.IsActive);

            entry.OnSelected += () =>
            {
                _selectedBladeServer = blade.Uid;
                UpdateSelectionState(state);
            };

            entry.OnEject += () => OnEjectBladeServer?.Invoke(blade.Uid);

            BladeServersList.AddChild(entry);
        }

        RecallButton.Disabled = !hasActive;
    }

    private void UpdateStatus(HologramConsoleBoundUserInterfaceState state)
    {
        if (state.BladeServers.Count == 0)
        {
            StatusLabel.Text = "No blade servers available";
            StatusLabel.FontColorOverride = Color.FromHex("#ef4444");

            ActiveIndicator.Text = " ● NO DATA ";
            ActiveIndicator.FontColorOverride = Color.FromHex("#6b7280");

            return;
        }

        StatusLabel.Text = $"{state.BladeServers.Count} hologram(s) available";
        StatusLabel.FontColorOverride = Color.FromHex("#7dd3fc");

        var hasActive = state.ActiveHologram != null || state.ActiveCount > 0;

        ActiveIndicator.Text = hasActive ? "● ACTIVE" : "● READY";
        ActiveIndicator.FontColorOverride =
            hasActive
                ? Color.FromHex("#10b981")
                : Color.FromHex("#fbbf24");
    }

    private void UpdateSelectionState(HologramConsoleBoundUserInterfaceState state)
    {
        foreach (var child in BladeServersList.Children)
        {
            if (child is BladeServerListEntry entry)
                entry.SetSelected(entry.BladeServerUid == _selectedBladeServer);
        }

        if (_currentState != null)
            UpdateNavMapBlips(_currentState);

        if (state.IsPortable)
        {
            ProjectButton.Disabled =
                _selectedBladeServer == null ||
                state.ActiveCount >= state.MaxActive;

            ProjectButton.Text =
                state.ActiveCount > 0
                    ? "▶ PROJECT ANOTHER"
                    : "▶ PROJECT";
        }
        else
        {
            ProjectButton.Disabled =
                _selectedBladeServer == null ||
                _selectedProjector == null ||
                state.ActiveHologram != null;
        }
    }
}

public sealed class BladeServerListEntry : PanelContainer
{
    public NetEntity BladeServerUid { get; }
    public event Action? OnSelected;
    public event Action? OnEject;

    private readonly PanelContainer _panel;

    public BladeServerListEntry(BladeServerInfo info, bool isActive)
    {
        BladeServerUid = info.Uid;

        _panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = isActive ? Color.FromHex("#0f172a") : Color.FromHex("#1f2937"),
                BorderColor = isActive ? Color.FromHex("#10b981") : Color.FromHex("#374151"),
                BorderThickness = new Thickness(2)
            },
            Margin = new Thickness(2)
        };

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 6),
            SeparationOverride = 8
        };

        var infoContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 2
        };

        var nameLabel = new Label
        {
            Text = info.HologramName,
            FontColorOverride = Color.FromHex("#e5e7eb")
        };
        infoContainer.AddChild(nameLabel);

        if (isActive)
        {
            var statusLabel = new RichTextLabel
            {
                SetHeight = 16
            };
            statusLabel.SetMessage(
                FormattedMessage.FromMarkupOrThrow("[color=#10b981]ACTIVE PROJECTION[/color]"));
            infoContainer.AddChild(statusLabel);
        }

        container.AddChild(infoContainer);

        var ejectButton = new Button
        {
            Text = "⏏ EJECT",
            MinWidth = 70,
            MinHeight = 30,
            Disabled = isActive
        };
        ejectButton.OnPressed += _ => OnEject?.Invoke();
        container.AddChild(ejectButton);

        var selectButton = new Button
        {
            Text = "SELECT",
            MinWidth = 70,
            MinHeight = 30,
            Disabled = isActive
        };
        selectButton.OnPressed += _ => OnSelected?.Invoke();
        container.AddChild(selectButton);

        _panel.AddChild(container);
        AddChild(_panel);
    }

    public void SetSelected(bool selected)
    => _panel.PanelOverride = new StyleBoxFlat
        {
        BackgroundColor = selected ? Color.FromHex("#1e3a8a") : Color.FromHex("#1f2937"),
        BorderColor = selected ? Color.FromHex("#3b82f6") : Color.FromHex("#374151"),
        BorderThickness = new Thickness(2)
    };
}
