using System.Linq;
using Content.Client.Pinpointer.UI;
using Content.Shared._Starlight.Holograms;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Holograms.UI;

[GenerateTypedNameReferences]
public sealed partial class HologramConsoleWindow : BaseWindow
{
    private readonly IEntityManager _entManager;
    private readonly SpriteSystem _spriteSystem;

    private NetEntity? _selectedBladeServer;
    private NetEntity? _selectedProjector;
    private bool _isPortableMode;
    private readonly Texture? _blipTexture;
    private HologramConsoleBoundUserInterfaceState? _currentState;

    public event Action<NetEntity, NetEntity>? OnProjectHologram;
    public event Action<NetEntity?>? OnRecallHologram;
    public event Action<NetEntity>? OnEjectBladeServer;
    public event Action<bool>? OnToggleCarry;

    public HologramConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();
        _spriteSystem = _entManager.System<SpriteSystem>();

        _blipTexture = _spriteSystem.Frame0(
            new SpriteSpecifier.Texture(
                new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));

        NavMap.Visible = false;
        NoServerOverlay.Visible = true;

        ProjectButton.OnPressed += _ =>
        {
            if (_selectedBladeServer is not { } selectedBladeServer)
                return;

            var projector = _isPortableMode
                ? NetEntity.Invalid
                : (_selectedProjector ?? NetEntity.Invalid);

            OnProjectHologram?.Invoke(selectedBladeServer, projector);
        };

        RecallButton.OnPressed += _ =>
        {
            var selected = GetSelectedBladeInfo();
            OnRecallHologram?.Invoke(selected is { IsActive: true }
                ? selected.Uid
                : null);
        };

        AllowCarryCheckbox.OnToggled += args => OnToggleCarry?.Invoke(args.Pressed);
        NavMap.TrackedEntitySelectedAction += OnProjectorSelectedFromMap;
    }

    private void OnProjectorSelectedFromMap(NetEntity? netEntity)
    {
        if (netEntity is not { } selectedProjector)
            return;

        _selectedProjector = selectedProjector;
        UpdateSelectionStateAfterChange();
    }

    private void SetupNavMap(HologramConsoleBoundUserInterfaceState state)
    {
        if (_blipTexture == null || state.ProjectorCoordinates.Count == 0)
        {
            NavMap.Visible = false;
            NoServerOverlay.Visible = true;
            NoServerMapLabel.Text = "NO SAME-GRID PROJECTORS";
            return;
        }

        NoServerOverlay.Visible = false;
        NavMap.Visible = true;

        var firstCoords = _entManager.GetCoordinates(state.ProjectorCoordinates.Values.First());
        if (_entManager.TryGetComponent(firstCoords.EntityId, out TransformComponent? xform))
            NavMap.MapUid = xform.GridUid;

        UpdateNavMapBlips(state);
        NavMap.ForceNavMapUpdate();
    }

    private void UpdateNavMapBlips(HologramConsoleBoundUserInterfaceState state)
    {
        if (_blipTexture == null)
            return;

        NavMap.TrackedEntities.Clear();

        foreach (var (netEntity, netCoords) in state.ProjectorCoordinates)
        {
            var coords = _entManager.GetCoordinates(netCoords);
            var selected = netEntity == _selectedProjector;
            var color = NavMap.GetProjectorColor(selected);

            NavMap.TrackedEntities[netEntity] =
                new NavMapBlip(coords, _blipTexture, color, true, true);
        }
    }

    private void UpdateSelectionStateAfterChange()
    {
        if (_currentState == null)
            return;

        UpdateSelectionState(_currentState);
        UpdateNavMapBlips(_currentState);
    }

    public void UpdateState(HologramConsoleBoundUserInterfaceState state)
    {
        _currentState = state;
        _isPortableMode = state.IsPortable;

        ValidateSelections(state);

        BatteryPanel.Visible = state.IsPortable;
        SettingsPanel.Visible = state.IsPortable;
        ModeLabel.Visible = state.IsPortable;

        MapPanel.Visible = state.ShowMap && !state.IsPortable;
        LeftPanel.Visible = state.ShowBladeServerPanel;
        ProjectButton.Visible = state.ShowProjectButton;
        RecallButton.Visible = state.ShowRecallButton;
        ControlsPanel.Visible = state.ShowProjectButton || state.ShowRecallButton;

        if (state.IsPortable)
        {
            ModeLabel.Text = "PORTABLE MODE";

            NavMap.Visible = false;
            NoServerOverlay.Visible = false;

            UpdateBattery(state);

            AllowCarryCheckbox.Pressed = state.AllowCarry;

            PortableInfoLabel.Visible = true;
            PortableInfoLabel.Text = $"Active: {state.ActiveCount} / {state.MaxActive}";
        }
        else
        {
            PortableInfoLabel.Visible = false;

            if (!state.HasServer)
            {
                HandleNoServerState();
                return;
            }

            NoBladeServersLabel.Visible = false;
            SetupNavMap(state);
        }

        UpdateBladeServerList(state);
        UpdateStatus(state);

        ProjectorCountLabel.Text =
            state.Projectors.Count > 0
                ? $" {state.Projectors.Count} Same-Grid Projectors "
                : " No Same-Grid Projectors ";

        UpdateSelectionState(state);
    }

    private void ValidateSelections(HologramConsoleBoundUserInterfaceState state)
    {
        if (_selectedBladeServer is { } selectedBladeServer && state.BladeServers.All(x => x.Uid != selectedBladeServer))
            _selectedBladeServer = null;

        if (_selectedBladeServer == null && state.BladeServers.Count > 0)
        {
            var inactive = state.BladeServers.FirstOrDefault(x => !x.IsActive);
            _selectedBladeServer = (inactive ?? state.BladeServers.First()).Uid;
        }

        if (_selectedProjector is { } selectedProjector && state.Projectors.All(x => x.Uid != selectedProjector))
            _selectedProjector = null;

        if (!state.IsPortable && _selectedProjector == null && state.Projectors.Count > 0)
            _selectedProjector = state.Projectors.First().Uid;
    }

    private BladeServerInfo? GetSelectedBladeInfo()
    {
        if (_currentState == null || _selectedBladeServer is not { } selectedBladeServer)
            return null;

        return _currentState.BladeServers.FirstOrDefault(x => x.Uid == selectedBladeServer);
    }

    private void HandleNoServerState()
    {
        NoBladeServersLabel.Visible = true;
        NoServerOverlay.Visible = true;
        NavMap.Visible = false;

        BladeServersList.RemoveAllChildren();

        StatusLabel.Text = "No same-grid hologram hardware";
        StatusLabel.FontColorOverride = Color.FromHex("#ef4444");

        ActiveIndicator.Text = "● OFFLINE";
        ActiveIndicator.FontColorOverride = Color.FromHex("#ef4444");

        ProjectButton.Disabled = true;
        RecallButton.Disabled = true;

        ProjectorCountLabel.Text = " No Same-Grid Projectors ";
    }

    private void UpdateBattery(HologramConsoleBoundUserInterfaceState state)
    {
        if (state.BatteryPercent is not { } percent)
            return;

        BatteryBar.Value = Math.Clamp(percent / 100f, 0f, 1f);
        BatteryLabel.Text = $"{percent:F0}%";

        var color = percent switch
        {
            > 50 => "#10b981",
            > 20 => "#fbbf24",
            _ => "#ef4444"
        };

        BatteryLabel.FontColorOverride = Color.FromHex(color);
        BatteryBar.ForegroundStyleBoxOverride =
            new StyleBoxFlat { BackgroundColor = Color.FromHex(color) };
    }

    private void UpdateBladeServerList(HologramConsoleBoundUserInterfaceState state)
    {
        BladeServersList.RemoveAllChildren();

        if (state.BladeServers.Count == 0)
        {
            NoBladeServersLabel.Visible = true;
            RecallButton.Disabled = true;
            return;
        }

        NoBladeServersLabel.Visible = false;

        foreach (var blade in state.BladeServers)
        {
            var entry = new BladeServerListEntry(blade, state.IsPortable);

            entry.OnSelected += () =>
            {
                _selectedBladeServer = blade.Uid;
                UpdateSelectionState(state);
            };

            entry.OnEject += () => OnEjectBladeServer?.Invoke(blade.Uid);

            BladeServersList.AddChild(entry);
        }

        RecallButton.Disabled = state.ActiveCount <= 0;
    }

    private void UpdateStatus(HologramConsoleBoundUserInterfaceState state)
    {
        if (state.BladeServers.Count == 0)
        {
            StatusLabel.Text = "No blade servers available";
            StatusLabel.FontColorOverride = Color.FromHex("#ef4444");

            ActiveIndicator.Text = " ● NO DATA ";
            ActiveIndicator.FontColorOverride = Color.FromHex("#6b7280");

            return;
        }

        var activeText = state.ActiveCount == 1 ? "1 active" : $"{state.ActiveCount} active";
        StatusLabel.Text = $"{state.BladeServers.Count} hologram(s) available, {activeText}";
        StatusLabel.FontColorOverride = Color.FromHex("#7dd3fc");

        ActiveIndicator.Text = state.ActiveCount > 0 ? "● ACTIVE" : "● READY";
        ActiveIndicator.FontColorOverride =
            state.ActiveCount > 0
                ? Color.FromHex("#10b981")
                : Color.FromHex("#fbbf24");
    }

    private void UpdateSelectionState(HologramConsoleBoundUserInterfaceState state)
    {
        foreach (var child in BladeServersList.Children)
        {
            if (child is BladeServerListEntry entry)
                entry.SetSelected(entry.BladeServerUid == _selectedBladeServer);
        }

        UpdateNavMapBlips(state);

        var selected = GetSelectedBladeInfo();
        var selectedActive = selected?.IsActive == true;
        var maxed = state.MaxActive > 0 && state.ActiveCount >= state.MaxActive;

        if (state.IsPortable)
        {
            ProjectButton.Disabled =
                selected == null ||
                selectedActive ||
                (!selectedActive && maxed);

            ProjectButton.Text = selectedActive
                ? "▶ ALREADY PROJECTED"
                : state.ActiveCount > 0
                    ? "▶ PROJECT ANOTHER"
                    : "▶ PROJECT";
        }
        else
        {
            ProjectButton.Disabled =
                selected == null ||
                _selectedProjector == null ||
                (!selectedActive && maxed);

            ProjectButton.Text = selectedActive
                ? "▶ MOVE TO PROJECTOR"
                : state.ActiveCount > 0
                    ? "▶ PROJECT ANOTHER"
                    : "▶ PROJECT";
        }

        if (selectedActive)
            RecallButton.Text = "◼ RECALL SELECTED";
        else
            RecallButton.Text = state.ActiveCount > 1 ? "◼ RECALL ALL" : "◼ RECALL";

        RecallButton.Disabled = state.ActiveCount <= 0;
    }
}

public sealed class BladeServerListEntry : PanelContainer
{
    public NetEntity BladeServerUid { get; }
    public event Action? OnSelected;
    public event Action? OnEject;

    private readonly PanelContainer _panel;
    private readonly bool _isActive;

    public BladeServerListEntry(BladeServerInfo info, bool _)
    {
        BladeServerUid = info.Uid;
        _isActive = info.IsActive;

        _panel = new PanelContainer
        {
            PanelOverride = GetPanelStyle(false),
            Margin = new Thickness(2)
        };

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 6),
            SeparationOverride = 8
        };

        var infoContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 2
        };

        var nameLabel = new Label
        {
            Text = info.HologramName,
            FontColorOverride = Color.FromHex("#e5e7eb")
        };
        infoContainer.AddChild(nameLabel);

        var statusLabel = new RichTextLabel
        {
            SetHeight = 16
        };
        statusLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
            info.IsActive
                ? "[color=#10b981]ACTIVE PROJECTION[/color]"
                : "[color=#7dd3fc]READY[/color]"));
        infoContainer.AddChild(statusLabel);

        container.AddChild(infoContainer);

        var ejectButton = new Button
        {
            Text = "⏏ EJECT",
            MinWidth = 70,
            MinHeight = 30,
            Disabled = true
        };
        ejectButton.OnPressed += _ => OnEject?.Invoke();
        container.AddChild(ejectButton);

        var selectButton = new Button
        {
            Text = info.IsActive ? "SELECT" : "SELECT",
            MinWidth = 70,
            MinHeight = 30
        };
        selectButton.OnPressed += _ => OnSelected?.Invoke();
        container.AddChild(selectButton);

        _panel.AddChild(container);
        AddChild(_panel);
    }

    public void SetSelected(bool selected)
        => _panel.PanelOverride = GetPanelStyle(selected);

    private StyleBoxFlat GetPanelStyle(bool selected)
    {
        if (selected)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1e3a8a"),
                BorderColor = Color.FromHex("#3b82f6"),
                BorderThickness = new Thickness(2)
            };
        }

        return new StyleBoxFlat
        {
            BackgroundColor = _isActive ? Color.FromHex("#0f172a") : Color.FromHex("#1f2937"),
            BorderColor = _isActive ? Color.FromHex("#10b981") : Color.FromHex("#374151"),
            BorderThickness = new Thickness(2)
        };
    }
}
