using System;
using System.Linq;
using Content.Shared._Starlight.AutoMod;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.AutoMod.UI;

[GenerateTypedNameReferences]
public sealed partial class AutoModWindow : DefaultWindow
{
    public event Action<string>? TabSelected;
    public event Action<string>? TesterSubmitted;

    public AutoModWindow()
    {
        RobustXamlLoader.Load(this);

        DashboardButton.OnPressed += _ => TabSelected?.Invoke("Dashboard");
        IncidentsButton.OnPressed += _ => TabSelected?.Invoke("Incident Log");
        ApprovalsButton.OnPressed += _ => TabSelected?.Invoke("Approval Queue");
        PlayersButton.OnPressed += _ => TabSelected?.Invoke("Player Lookup");
        RulesButton.OnPressed += _ => TabSelected?.Invoke("Rules");
        TesterButton.OnPressed += _ => TabSelected?.Invoke("Tester");
        DiscordButton.OnPressed += _ => TabSelected?.Invoke("Discord Logs");
        HealthButton.OnPressed += _ => TabSelected?.Invoke("Sync / Health");
        SettingsButton.OnPressed += _ => TabSelected?.Invoke("Settings");
        RunTesterButton.OnPressed += _ => TesterSubmitted?.Invoke(TesterInput.Text);
    }

    public void Populate(AutoModUiState state)
    {
        StatusLabel.Text = $"Ruleset: {state.RulesetVersion} | Enabled: {state.Enabled} | Shadow: {state.ShadowMode} | NullLink: {(state.NullLinkEnabled ? state.NullLinkHealthy ? "Synced" : "Degraded" : "Disabled")} | Outbox: {state.UnsyncedIncidents}";
        ShowDashboard(state);
    }

    public void ShowDashboard(AutoModUiState state)
    {
        MainTitle.Text = "Dashboard";
        TesterInput.Visible = false;
        RunTesterButton.Visible = false;
        MainText.SetMessage($"Recent incidents: {state.RecentIncidents.Count}\nRules: {state.Rules.Count}\nPending approvals: {state.PendingApprovals}\nDiscord: {(state.DiscordEnabled ? "Enabled" : "Disabled")}");
    }

    public void ShowTab(string tab, AutoModUiState? state)
    {
        MainTitle.Text = tab;
        TesterInput.Visible = tab == "Tester";
        RunTesterButton.Visible = tab == "Tester";

        MainText.SetMessage(tab switch
        {
            "Incident Log" => FormatIncidents(state),
            "Rules" => FormatRules(state),
            "Tester" => "Enter text below and run tester.",
            "Sync / Health" => state == null ? "No state." : $"NullLink enabled: {state.NullLinkEnabled}\nNullLink healthy: {state.NullLinkHealthy}\nUnsynced incidents: {state.UnsyncedIncidents}",
            "Discord Logs" => state == null ? "No state." : $"Discord enabled: {state.DiscordEnabled}",
            _ => "This tab is backed by AutoModUiState and can be expanded with native controls.",
        });
    }

    public void ShowTestResult(AutoModTestResult result)
    {
        MainTitle.Text = "Tester Result";
        TesterInput.Visible = true;
        RunTesterButton.Visible = true;
        MainText.SetMessage($"Matched: {result.Matched}\nRule: {result.RuleId}\nAction: {result.ActionSummary}\nCancel speech: {result.CancelSpeech}\nApproval: {result.RequiresApproval}\nDiscord: {result.WouldDiscordLog}\nNormalized: {result.NormalizedText}\nFeedback: {result.PlayerFeedback}");
    }

    private static string FormatIncidents(AutoModUiState? state)
    {
        if (state == null || state.RecentIncidents.Count == 0)
            return "No incidents.";

        return string.Join('\n', state.RecentIncidents.Take(100).Select(x => $"{x.CreatedAtUtc:u} | {x.PlayerNameAtTime} | {x.RuleId} | {x.ActionTaken} | {x.Status}"));
    }

    private static string FormatRules(AutoModUiState? state)
    {
        if (state == null || state.Rules.Count == 0)
            return "No rules.";

        return string.Join('\n', state.Rules.Select(x => $"{x.Enabled} | {x.Priority} | {x.Name} | {x.Category} | {x.Severity} | {x.MatchKind} | {x.ActionSummary}"));
    }
}
