using System.Globalization;
using System.Linq;
using Content.Shared._Starlight.AutoMod;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.AutoMod.UI;

[GenerateTypedNameReferences]
public sealed partial class AutoModWindow : DefaultWindow
{
    public event Action<string>? TabSelected;
    public event Action<string, string, string?, int>? TesterSubmitted;
    public event Action? CreateTemplateRuleRequested;
    public event Action<AutoModEditableRule, string>? SaveRuleRequested;
    public event Action<string, string>? DeleteRuleRequested;
    public event Action<string, bool, string>? ToggleRuleRequested;

    private AutoModUiState? _state;
    private AutoModEditableRule? _workingRule;
    private int _levelIndex;

    private bool _enabled;
    private bool _requireBoundary = true;
    private bool _showMatchedToken = true;
    private bool _cancelSpeech = true;
    private bool _notifyAdmins = true;
    private bool _createNote = true;
    private bool _appealable = true;
    private bool _allowSpeechWhilePending;

    private AutoModSeverity _severity = AutoModSeverity.Low;
    private AutoModSeverity _actionSeverity = AutoModSeverity.Low;
    private AutoModMatchKind _matchKind = AutoModMatchKind.WordSet;
    private AutoModNormalizationMode _normalization = AutoModNormalizationMode.Basic;
    private AutoModEscalationScopeKind _scope = AutoModEscalationScopeKind.Rule;
    private AutoModEvidenceMode _evidenceMode = AutoModEvidenceMode.RedactedPreview;
    private AutoModDiscordLogMode _discordMode = AutoModDiscordLogMode.PunishmentsOnly;
    private AutoModActionType _discordMinimum = AutoModActionType.CreateNote;
    private AutoModActionMode _actionMode = AutoModActionMode.Immediate;
    private AutoModActionType _actionType = AutoModActionType.Warn;

    public AutoModWindow()
    {
        RobustXamlLoader.Load(this);

        DashboardButton.OnPressed += _ => SelectTab("Dashboard");
        IncidentsButton.OnPressed += _ => SelectTab("Incident Log");
        ApprovalsButton.OnPressed += _ => SelectTab("Approval Queue");
        PlayersButton.OnPressed += _ => SelectTab("Player Lookup");
        RulesButton.OnPressed += _ => SelectTab("Rules");
        TesterButton.OnPressed += _ => SelectTab("Tester");
        DiscordButton.OnPressed += _ => SelectTab("Discord Logs");
        HealthButton.OnPressed += _ => SelectTab("Sync / Health");
        SettingsButton.OnPressed += _ => SelectTab("Settings");

        RunTesterButton.OnPressed += _ => TesterSubmitted?.Invoke(
            TesterInput.Text ?? string.Empty,
            TesterChannel.Text ?? "OOC",
            string.IsNullOrWhiteSpace(TesterRuleId.Text) ? null : TesterRuleId.Text,
            ParseInt(TesterMockPoints.Text, 0));

        CreateRuleButton.OnPressed += _ => CreateTemplateRuleRequested?.Invoke();
        LoadRuleButton.OnPressed += _ => LoadRuleById(SelectedRuleId.Text ?? string.Empty);
        SaveRuleButton.OnPressed += _ => SaveLoadedRule();
        EnableRuleButton.OnPressed += _ => ToggleLoadedRule(true);
        DisableRuleButton.OnPressed += _ => ToggleLoadedRule(false);
        DeleteRuleButton.OnPressed += _ => DeleteLoadedRule();

        ToggleEnabledButton.OnPressed += _ =>
        {
            _enabled = !_enabled;
            RefreshToggleButtons();
        };
        SeverityButton.OnPressed += _ =>
        {
            _severity = NextEnum(_severity);
            RefreshToggleButtons();
        };
        MatchKindButton.OnPressed += _ =>
        {
            _matchKind = NextEnum(_matchKind);
            RefreshToggleButtons();
        };
        NormalizationButton.OnPressed += _ =>
        {
            _normalization = NextEnum(_normalization);
            RefreshToggleButtons();
        };
        BoundaryButton.OnPressed += _ =>
        {
            _requireBoundary = !_requireBoundary;
            RefreshToggleButtons();
        };
        ScopeButton.OnPressed += _ =>
        {
            _scope = NextEnum(_scope);
            RefreshToggleButtons();
        };
        EvidenceModeButton.OnPressed += _ =>
        {
            _evidenceMode = NextEnum(_evidenceMode);
            RefreshToggleButtons();
        };
        ShowTokenButton.OnPressed += _ =>
        {
            _showMatchedToken = !_showMatchedToken;
            RefreshToggleButtons();
        };
        DiscordModeButton.OnPressed += _ =>
        {
            _discordMode = NextEnum(_discordMode);
            RefreshToggleButtons();
        };
        DiscordMinimumButton.OnPressed += _ =>
        {
            _discordMinimum = NextEnum(_discordMinimum);
            RefreshToggleButtons();
        };
        CancelSpeechButton.OnPressed += _ =>
        {
            _cancelSpeech = !_cancelSpeech;
            RefreshToggleButtons();
        };
        NotifyAdminsButton.OnPressed += _ =>
        {
            _notifyAdmins = !_notifyAdmins;
            RefreshToggleButtons();
        };
        ActionModeButton.OnPressed += _ =>
        {
            _actionMode = NextEnum(_actionMode);
            RefreshToggleButtons();
        };
        ActionTypeButton.OnPressed += _ =>
        {
            _actionType = NextEnum(_actionType);
            RefreshToggleButtons();
        };
        CreateNoteButton.OnPressed += _ =>
        {
            _createNote = !_createNote;
            RefreshToggleButtons();
        };
        ActionSeverityButton.OnPressed += _ =>
        {
            _actionSeverity = NextEnum(_actionSeverity);
            RefreshToggleButtons();
        };
        AppealableButton.OnPressed += _ =>
        {
            _appealable = !_appealable;
            RefreshToggleButtons();
        };
        ApprovalSpeechPendingButton.OnPressed += _ =>
        {
            _allowSpeechWhilePending = !_allowSpeechWhilePending;
            RefreshToggleButtons();
        };

        LoadLevelButton.OnPressed += _ =>
        {
            if (_workingRule == null)
                return;

            SaveCurrentLevelToWorkingRule();
            _levelIndex = Math.Clamp(ParseInt(LevelNumber.Text, 1) - 1, 0, Math.Max(0, _workingRule.Levels.Count - 1));
            LoadLevelIntoEditor(_levelIndex);
        };
        AddLevelButton.OnPressed += _ =>
        {
            EnsureWorkingRule();
            SaveCurrentLevelToWorkingRule();
            _workingRule!.Levels.Add(CreateDefaultLevel(_workingRule.Levels.Count + 1));
            _levelIndex = _workingRule.Levels.Count - 1;
            LoadLevelIntoEditor(_levelIndex);
            UpdateRuleListText();
        };
        RemoveLevelButton.OnPressed += _ =>
        {
            if (_workingRule == null || _workingRule.Levels.Count <= 1)
                return;

            _workingRule.Levels.RemoveAt(Math.Clamp(_levelIndex, 0, _workingRule.Levels.Count - 1));
            _levelIndex = Math.Clamp(_levelIndex, 0, _workingRule.Levels.Count - 1);
            LoadLevelIntoEditor(_levelIndex);
            UpdateRuleListText();
        };

        RefreshToggleButtons();
    }

    public void Populate(AutoModUiState state)
    {
        _state = state;
        StatusLabel.Text =
            $"Ruleset: {state.RulesetVersion} | Enabled: {state.Enabled} | Shadow: {state.ShadowMode} | " +
            $"NullLink: {(state.NullLinkEnabled ? state.NullLinkHealthy ? "Synced" : "Degraded" : "Disabled")} | " +
            $"Outbox: {state.UnsyncedIncidents}";

        UpdateRuleListText();

        if (_workingRule == null && state.EditableRules.Count > 0)
            LoadRuleIntoEditor(state.EditableRules[0]);

        ShowDashboard(state);
    }

    public void ShowTab(string tab, AutoModUiState? state)
    {
        _state = state ?? _state;
        MainTitle.Text = tab;
        InfoPanel.Visible = tab != "Rules" && tab != "Tester";
        TesterControls.Visible = tab == "Tester";
        RuleEditorControls.Visible = tab == "Rules";

        MainText.Text = tab switch
        {
            "Dashboard" => FormatDashboard(_state),
            "Incident Log" => FormatIncidents(_state),
            "Approval Queue" => "Approval requests will appear here when rules use Mode: RequireApproval. Use that mode for bans or low-confidence regex rules.",
            "Player Lookup" => "Player-specific AutoMod review belongs here. Until the player panel hook is expanded, use Incident Log to search recent events.",
            "Discord Logs" => _state == null ? "No state." : $"Discord enabled: {_state.DiscordEnabled}\nDiscord logging is async and should never block chat.",
            "Sync / Health" => _state == null ? "No state." : $"NullLink enabled: {_state.NullLinkEnabled}\nNullLink healthy: {_state.NullLinkHealthy}\nUnsynced incidents: {_state.UnsyncedIncidents}\nRule store: {_state.RuleStorePath}",
            "Settings" => "Global AutoMod settings are CVar-backed. Rule behaviour is edited in the Rules tab and saved in-game.",
            _ => string.Empty,
        };

        if (tab == "Rules")
        {
            UpdateRuleListText();
            if (_workingRule == null && _state?.EditableRules.Count > 0)
                LoadRuleIntoEditor(_state.EditableRules[0]);
        }
    }

    public void ShowTestResult(AutoModTestResult result)
    {
        MainTitle.Text = "Tester Result";
        InfoPanel.Visible = true;
        TesterControls.Visible = true;
        RuleEditorControls.Visible = false;
        MainText.Text =
            $"Matched: {result.Matched}\n" +
            $"Rule: {result.RuleId}\n" +
            $"Action: {result.ActionSummary}\n" +
            $"Cancel speech: {result.CancelSpeech}\n" +
            $"Approval required: {result.RequiresApproval}\n" +
            $"Discord would log: {result.WouldDiscordLog}\n" +
            $"Points: {result.PointsBefore} -> {result.PointsAfter}\n" +
            $"Normalized: {result.NormalizedText}\n" +
            $"Player feedback: {result.PlayerFeedback}\n" +
            $"Evidence: {result.EvidencePreview}";
    }

    public void ShowOperationResult(AutoModOperationResultMessage result)
    {
        MainTitle.Text = result.Success ? "AutoMod operation succeeded" : "AutoMod operation failed";
        InfoPanel.Visible = true;
        MainText.Text = result.Message;
    }

    private void SelectTab(string tab)
    {
        TabSelected?.Invoke(tab);
        ShowTab(tab, _state);
    }

    private void ShowDashboard(AutoModUiState state)
    {
        ShowTab("Dashboard", state);
    }

    private void UpdateRuleListText()
    {
        if (_state == null || _state.Rules.Count == 0)
        {
            RuleListLabel.Text = "No runtime rules yet. Click Create New Disabled Rule.";
            return;
        }

        RuleListLabel.Text = string.Join('\n', _state.Rules
            .OrderByDescending(x => x.Priority)
            .ThenBy(x => x.Id)
            .Select(x =>
                $"{(x.Enabled ? "ON " : "OFF")}  {x.Id}\n" +
                $"    {x.Name} | {x.Category} | {x.Severity} | {x.MatchKind}\n" +
                $"    {x.ActionSummary}"));
    }

    private static string FormatDashboard(AutoModUiState? state)
    {
        if (state == null)
            return "No AutoMod state yet.";

        var highSeverity = state.RecentIncidents.Count(x => x.Severity >= AutoModSeverity.High);
        return
            $"Recent incidents: {state.RecentIncidents.Count}\n" +
            $"High severity incidents: {highSeverity}\n" +
            $"Saved rules: {state.Rules.Count}\n" +
            $"Pending approvals: {state.PendingApprovals}\n" +
            $"Discord: {(state.DiscordEnabled ? "Enabled" : "Disabled")}\n" +
            $"Rule store: {state.RuleStorePath}\n\n" +
            "Rules are fully runtime-configurable. No YAML or PRs are needed for rule changes.";
    }

    private static string FormatIncidents(AutoModUiState? state)
    {
        if (state == null || state.RecentIncidents.Count == 0)
            return "No incidents.";

        return string.Join('\n', state.RecentIncidents.Take(100).Select(x =>
            $"{x.CreatedAtUtc:u} | {Age(x.CreatedAtUtc)} ago | {x.PlayerNameAtTime} | {x.Channel} | {x.RuleId} | {x.ActionTaken} | {x.Status}"));
    }

    private void LoadRuleById(string id)
    {
        if (_state == null)
            return;

        var rule = _state.EditableRules.FirstOrDefault(x => string.Equals(x.ID, id, StringComparison.OrdinalIgnoreCase));
        if (rule == null)
        {
            MainTitle.Text = "Rule not found";
            InfoPanel.Visible = true;
            MainText.Text = $"No AutoMod rule with ID '{id}' was found. Copy the ID exactly from the rule list.";
            return;
        }

        LoadRuleIntoEditor(rule);
    }

    private void LoadRuleIntoEditor(AutoModEditableRule rule)
    {
        _workingRule = rule;
        _levelIndex = 0;

        RuleId.Text = rule.ID;
        SelectedRuleId.Text = rule.ID;
        RuleName.Text = rule.Name;
        RuleDescription.Text = rule.Description ?? string.Empty;
        RuleCategory.Text = rule.Category;
        RulePriority.Text = rule.Priority.ToString(CultureInfo.InvariantCulture);
        RuleChannels.Text = string.Join(", ", rule.Channels);

        _enabled = rule.Enabled;
        _severity = rule.Severity;
        _matchKind = rule.Match.Kind;
        _normalization = rule.Match.Normalization;
        _requireBoundary = rule.Match.RequireWordBoundary;
        PatternEdit.Text = rule.Match.Pattern ?? string.Empty;
        SpamWindowSeconds.Text = Math.Max(1, (int) rule.Match.Window.TotalSeconds).ToString(CultureInfo.InvariantCulture);
        SpamMaxMessages.Text = rule.Match.MaxMessages.ToString(CultureInfo.InvariantCulture);
        SetText(WordsEdit, string.Join('\n', rule.Match.Words));
        SetText(AllowListEdit, string.Join('\n', rule.Match.AllowList));

        _scope = rule.Escalation.Scope;
        ScopeKey.Text = rule.Escalation.ScopeKey ?? string.Empty;
        PointsPerIncident.Text = rule.Escalation.PointsPerIncident.ToString(CultureInfo.InvariantCulture);
        DecayDays.Text = Math.Max(0, (int) rule.Escalation.Decay.TotalDays).ToString(CultureInfo.InvariantCulture);

        _evidenceMode = rule.Evidence.Mode;
        EvidencePreview.Text = rule.Evidence.MaxPreviewLength.ToString(CultureInfo.InvariantCulture);
        _showMatchedToken = rule.Evidence.ShowMatchedTokenToAdmins;

        _discordMode = rule.Discord.LogMode;
        _discordMinimum = rule.Discord.MinimumAction;

        if (_workingRule.Levels.Count == 0)
            _workingRule.Levels.Add(CreateDefaultLevel(1));

        LoadLevelIntoEditor(0);
        RefreshToggleButtons();
        ShowTab("Rules", _state);
    }

    private void LoadLevelIntoEditor(int index)
    {
        if (_workingRule == null)
            return;

        if (_workingRule.Levels.Count == 0)
            _workingRule.Levels.Add(CreateDefaultLevel(1));

        _levelIndex = Math.Clamp(index, 0, _workingRule.Levels.Count - 1);
        var level = _workingRule.Levels[_levelIndex];
        var primary = level.Actions.FirstOrDefault(x => x.Type != AutoModActionType.CreateNote)
            ?? level.Actions.FirstOrDefault()
            ?? new AutoModEditableAction { Type = AutoModActionType.Warn, Message = "Your message was blocked by AutoMod." };
        var note = level.Actions.FirstOrDefault(x => x.Type == AutoModActionType.CreateNote);

        LevelNumber.Text = (_levelIndex + 1).ToString(CultureInfo.InvariantCulture);
        LevelMinPoints.Text = level.MinPoints.ToString(CultureInfo.InvariantCulture);
        _cancelSpeech = level.CancelSpeech;
        _notifyAdmins = level.NotifyAdmins;
        _actionMode = level.ActionMode;
        _allowSpeechWhilePending = level.Approval.AllowSpeechWhilePending;
        ApprovalTimeoutMinutes.Text = Math.Max(1, (int) level.Approval.Timeout.TotalMinutes).ToString(CultureInfo.InvariantCulture);

        _actionType = primary.Type;
        WarnMessage.Text = primary.Message ?? string.Empty;
        KickBanReason.Text = primary.Reason ?? string.Empty;
        DurationMinutes.Text = Math.Max(0, (int) primary.Duration.TotalMinutes).ToString(CultureInfo.InvariantCulture);

        _createNote = note != null || primary.Type == AutoModActionType.CreateNote;
        var noteSource = note ?? primary;
        _actionSeverity = noteSource.Severity;
        NoteExpiryDays.Text = Math.Max(0, (int) noteSource.Expiry.TotalDays).ToString(CultureInfo.InvariantCulture);
        _appealable = noteSource.Appealable;

        RefreshToggleButtons();
    }

    private void SaveLoadedRule()
    {
        EnsureWorkingRule();
        SaveCurrentRuleToWorkingRule();
        SaveCurrentLevelToWorkingRule();
        SaveRuleRequested?.Invoke(_workingRule!, RuleEditReason.Text ?? "Saved from AutoMod UI");
    }

    private void DeleteLoadedRule()
    {
        var id = SelectedRuleId.Text ?? RuleId.Text ?? string.Empty;
        if (string.IsNullOrWhiteSpace(id))
            return;

        DeleteRuleRequested?.Invoke(id.Trim(), RuleEditReason.Text ?? "Deleted from AutoMod UI");
    }

    private void ToggleLoadedRule(bool enabled)
    {
        var id = SelectedRuleId.Text ?? RuleId.Text ?? string.Empty;
        if (string.IsNullOrWhiteSpace(id))
            return;

        ToggleRuleRequested?.Invoke(id.Trim(), enabled, RuleEditReason.Text ?? (enabled ? "Enabled from AutoMod UI" : "Disabled from AutoMod UI"));
    }

    private void EnsureWorkingRule()
    {
        if (_workingRule != null)
            return;

        var channels = new List<string>();
        channels.Add("OOC");
        channels.Add("LOOC");

        var levels = new List<AutoModEditableLevel>();
        levels.Add(CreateDefaultLevel(1));

        _workingRule = new AutoModEditableRule
        {
            ID = string.IsNullOrWhiteSpace(RuleId.Text) ? $"automod-rule-{DateTime.UtcNow:yyyyMMddHHmmss}" : RuleId.Text.Trim(),
            Name = string.IsNullOrWhiteSpace(RuleName.Text) ? "New AutoMod Rule" : RuleName.Text.Trim(),
            Enabled = false,
            Priority = 100,
            Category = "General",
            Severity = AutoModSeverity.Low,
            Channels = channels,
            Levels = levels,
            Source = "RuntimeUI",
        };
    }

    private void SaveCurrentRuleToWorkingRule()
    {
        if (_workingRule == null)
            return;

        _workingRule.ID = (RuleId.Text ?? string.Empty).Trim();
        _workingRule.Name = string.IsNullOrWhiteSpace(RuleName.Text) ? _workingRule.ID : RuleName.Text.Trim();
        _workingRule.Description = RuleDescription.Text?.Trim() ?? string.Empty;
        _workingRule.Enabled = _enabled;
        _workingRule.Priority = ParseInt(RulePriority.Text, 100);
        _workingRule.Category = string.IsNullOrWhiteSpace(RuleCategory.Text) ? "General" : RuleCategory.Text.Trim();
        _workingRule.Severity = _severity;
        _workingRule.Channels = SplitList(RuleChannels.Text).DefaultIfEmpty("OOC").ToList();
        _workingRule.Source = "RuntimeUI";

        _workingRule.AdminPolicy.AdminedUsers = AutoModAdminedPolicy.Ignore;
        _workingRule.AdminPolicy.DeadminnedUsers = AutoModAdminedPolicy.Moderate;
        _workingRule.AdminPolicy.IgnoreAdminChannels = true;

        _workingRule.Match.Kind = _matchKind;
        _workingRule.Match.WordSet = null;
        _workingRule.Match.Pattern = string.IsNullOrWhiteSpace(PatternEdit.Text) ? null : PatternEdit.Text;
        _workingRule.Match.Words = SplitList(GetText(WordsEdit)).ToList();
        _workingRule.Match.AllowList = SplitList(GetText(AllowListEdit)).ToList();
        _workingRule.Match.Normalization = _normalization;
        _workingRule.Match.RequireWordBoundary = _requireBoundary;
        _workingRule.Match.Window = TimeSpan.FromSeconds(Math.Max(1, ParseInt(SpamWindowSeconds.Text, 10)));
        _workingRule.Match.MaxMessages = Math.Max(1, ParseInt(SpamMaxMessages.Text, 5));
        _workingRule.Match.SimilarityThreshold = 0.85f;

        _workingRule.Evidence.Mode = _evidenceMode;
        _workingRule.Evidence.MaxPreviewLength = Math.Clamp(ParseInt(EvidencePreview.Text, 160), 8, 1000);
        _workingRule.Evidence.ShowMatchedTokenToAdmins = _showMatchedToken;

        _workingRule.Escalation.Scope = _scope;
        _workingRule.Escalation.ScopeKey = string.IsNullOrWhiteSpace(ScopeKey.Text) ? null : ScopeKey.Text.Trim();
        _workingRule.Escalation.PointsPerIncident = Math.Max(0, ParseInt(PointsPerIncident.Text, 1));
        _workingRule.Escalation.Decay = TimeSpan.FromDays(Math.Max(0, ParseInt(DecayDays.Text, 30)));
        _workingRule.Escalation.IncludeFalsePositives = false;
        _workingRule.Escalation.IncludeDecayed = false;

        var pingRolesOn = new List<AutoModActionType>();
        pingRolesOn.Add(AutoModActionType.Ban);

        _workingRule.Discord.LogMode = _discordMode;
        _workingRule.Discord.MinimumAction = _discordMinimum;
        _workingRule.Discord.PingRolesOn = pingRolesOn;
    }

    private void SaveCurrentLevelToWorkingRule()
    {
        if (_workingRule == null)
            return;

        if (_workingRule.Levels.Count == 0)
            _workingRule.Levels.Add(CreateDefaultLevel(1));

        _levelIndex = Math.Clamp(_levelIndex, 0, _workingRule.Levels.Count - 1);
        _workingRule.Levels[_levelIndex] = BuildLevelFromFields();
        _workingRule.Levels = _workingRule.Levels.OrderBy(x => x.MinPoints).ToList();
    }

    private AutoModEditableLevel BuildLevelFromFields()
    {
        var action = new AutoModEditableAction
        {
            Type = _actionType,
            Message = string.IsNullOrWhiteSpace(WarnMessage.Text) ? null : WarnMessage.Text,
            Reason = string.IsNullOrWhiteSpace(KickBanReason.Text) ? null : KickBanReason.Text,
            Duration = TimeSpan.FromMinutes(Math.Max(0, ParseInt(DurationMinutes.Text, 0))),
            Severity = _actionSeverity,
            Expiry = TimeSpan.FromDays(Math.Max(0, ParseInt(NoteExpiryDays.Text, 30))),
            Appealable = _appealable,
        };

        var actions = new List<AutoModEditableAction>();
        if (_actionType != AutoModActionType.LogOnly)
            actions.Add(action);

        if (_createNote && _actionType != AutoModActionType.CreateNote)
        {
            actions.Add(new AutoModEditableAction
            {
                Type = AutoModActionType.CreateNote,
                Severity = _actionSeverity,
                Expiry = TimeSpan.FromDays(Math.Max(0, ParseInt(NoteExpiryDays.Text, 30))),
                Appealable = _appealable,
            });
        }

        if (actions.Count == 0)
            actions.Add(new AutoModEditableAction { Type = AutoModActionType.LogOnly });

        return new AutoModEditableLevel
        {
            MinPoints = Math.Max(1, ParseInt(LevelMinPoints.Text, 1)),
            CancelSpeech = _cancelSpeech,
            NotifyAdmins = _notifyAdmins,
            ActionMode = _actionMode,
            Approval = new AutoModEditableApproval
            {
                Timeout = TimeSpan.FromMinutes(Math.Max(1, ParseInt(ApprovalTimeoutMinutes.Text, 3))),
                RequiredPermission = _actionType == AutoModActionType.Ban ? "AutoModAuthorizeBan" : "AutoModAuthorizeAction",
                AllowSpeechWhilePending = _allowSpeechWhilePending,
            },
            Actions = actions,
        };
    }

    private static AutoModEditableLevel CreateDefaultLevel(int number)
    {
        var actions = new List<AutoModEditableAction>();

        actions.Add(new AutoModEditableAction
        {
            Type = AutoModActionType.Warn,
            Message = "Your message was blocked by AutoMod.",
            Severity = AutoModSeverity.Low,
            Expiry = TimeSpan.FromDays(30),
            Appealable = true,
        });

        actions.Add(new AutoModEditableAction
        {
            Type = AutoModActionType.CreateNote,
            Severity = AutoModSeverity.Low,
            Expiry = TimeSpan.FromDays(30),
            Appealable = true,
        });

        return new AutoModEditableLevel
        {
            MinPoints = Math.Max(1, number),
            CancelSpeech = true,
            NotifyAdmins = true,
            ActionMode = AutoModActionMode.Immediate,
            Approval = new AutoModEditableApproval
            {
                Timeout = TimeSpan.FromMinutes(3),
                RequiredPermission = "AutoModAuthorizeAction",
                AllowSpeechWhilePending = false,
            },
            Actions = actions,
        };
    }

    private void RefreshToggleButtons()
    {
        ToggleEnabledButton.Text = $"Enabled: {YesNo(_enabled)}";
        SeverityButton.Text = $"Severity: {_severity}";
        MatchKindButton.Text = $"Match: {_matchKind}";
        NormalizationButton.Text = $"Normalize: {_normalization}";
        BoundaryButton.Text = $"Whole words: {YesNo(_requireBoundary)}";
        ScopeButton.Text = $"Scope: {_scope}";
        EvidenceModeButton.Text = $"Evidence: {_evidenceMode}";
        ShowTokenButton.Text = $"Show match: {YesNo(_showMatchedToken)}";
        DiscordModeButton.Text = $"Discord: {_discordMode}";
        DiscordMinimumButton.Text = $"Min action: {_discordMinimum}";
        CancelSpeechButton.Text = $"Block speech: {YesNo(_cancelSpeech)}";
        NotifyAdminsButton.Text = $"Notify admins: {YesNo(_notifyAdmins)}";
        ActionModeButton.Text = $"Mode: {_actionMode}";
        ActionTypeButton.Text = $"Action: {_actionType}";
        CreateNoteButton.Text = $"Create note: {YesNo(_createNote)}";
        ActionSeverityButton.Text = $"Note severity: {_actionSeverity}";
        AppealableButton.Text = $"Appealable: {YesNo(_appealable)}";
        ApprovalSpeechPendingButton.Text = $"Allow speech pending: {YesNo(_allowSpeechWhilePending)}";
    }

    private static string YesNo(bool value) => value ? "Yes" : "No";

    private static T NextEnum<T>(T current) where T : struct, Enum
    {
        var values = Enum.GetValues<T>();
        var index = Array.IndexOf(values, current);
        return values[(index + 1) % values.Length];
    }

    private static int ParseInt(string? value, int fallback)
    {
        return int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var parsed)
            ? parsed
            : fallback;
    }

    private static IEnumerable<string> SplitList(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            yield break;

        foreach (var part in value.Split(new[] { '\n', '\r', ',' }, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (!string.IsNullOrWhiteSpace(part))
                yield return part.Trim();
        }
    }

    private static string Age(DateTime utc)
    {
        var span = DateTime.UtcNow - utc;
        if (span.TotalDays >= 1)
            return $"{(int) span.TotalDays}d";
        if (span.TotalHours >= 1)
            return $"{(int) span.TotalHours}h";
        if (span.TotalMinutes >= 1)
            return $"{(int) span.TotalMinutes}m";
        return $"{Math.Max(0, (int) span.TotalSeconds)}s";
    }

    private static string GetText(TextEdit edit)
    {
        return edit.TextLength == 0
            ? string.Empty
            : Rope.CollapseSubstring(edit.TextRope, 0..edit.TextLength);
    }

    private static void SetText(TextEdit edit, string text)
    {
        edit.TextRope = Rope.Leaf.Empty;
        edit.CursorPosition = default;
        edit.SelectionStart = default;

        if (!string.IsNullOrEmpty(text))
            edit.InsertAtCursor(text);
    }
}
