using System;
using System.Linq;
using Content.Shared._Starlight.AutoMod;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.AutoMod.UI;

[GenerateTypedNameReferences]
public sealed partial class AutoModWindow : DefaultWindow
{
    public event Action<string>? TabSelected;
    public event Action<string>? TesterSubmitted;
    public event Action? CreateTemplateRuleRequested;
    public event Action<string, string>? SaveRuleJsonRequested;
    public event Action<string, string>? DeleteRuleRequested;
    public event Action<string, bool, string>? ToggleRuleRequested;

    private AutoModUiState? _state;

    public AutoModWindow()
    {
        RobustXamlLoader.Load(this);

        DashboardButton.OnPressed += _ => SelectTab("Dashboard");
        IncidentsButton.OnPressed += _ => SelectTab("Incident Log");
        ApprovalsButton.OnPressed += _ => SelectTab("Approval Queue");
        PlayersButton.OnPressed += _ => SelectTab("Player Lookup");
        RulesButton.OnPressed += _ => SelectTab("Rules");
        TesterButton.OnPressed += _ => SelectTab("Tester");
        DiscordButton.OnPressed += _ => SelectTab("Discord Logs");
        HealthButton.OnPressed += _ => SelectTab("Sync / Health");
        SettingsButton.OnPressed += _ => SelectTab("Settings");

        RunTesterButton.OnPressed += _ => TesterSubmitted?.Invoke(TesterInput.Text ?? string.Empty);
        CreateRuleButton.OnPressed += _ => CreateTemplateRuleRequested?.Invoke();
        SaveRuleButton.OnPressed += _ => SaveRuleJsonRequested?.Invoke(GetText(RuleJsonEditor), RuleEditReason.Text ?? "Saved from AutoMod UI");
        EnableRuleButton.OnPressed += _ => ToggleRuleRequested?.Invoke(SelectedRuleId.Text ?? string.Empty, true, RuleEditReason.Text ?? "Enabled from AutoMod UI");
        DisableRuleButton.OnPressed += _ => ToggleRuleRequested?.Invoke(SelectedRuleId.Text ?? string.Empty, false, RuleEditReason.Text ?? "Disabled from AutoMod UI");
        DeleteRuleButton.OnPressed += _ => DeleteRuleRequested?.Invoke(SelectedRuleId.Text ?? string.Empty, RuleEditReason.Text ?? "Deleted from AutoMod UI");
    }

    public void Populate(AutoModUiState state)
    {
        _state = state;
        StatusLabel.Text = $"Ruleset: {state.RulesetVersion} | Enabled: {state.Enabled} | Shadow: {state.ShadowMode} | NullLink: {(state.NullLinkEnabled ? state.NullLinkHealthy ? "Synced" : "Degraded" : "Disabled")} | Outbox: {state.UnsyncedIncidents}";
        ShowDashboard(state);
    }

    public void ShowTab(string tab, AutoModUiState? state)
    {
        _state = state ?? _state;
        MainTitle.Text = tab;
        TesterControls.Visible = tab == "Tester";
        RuleEditorControls.Visible = tab == "Rules";

        MainText.Text = tab switch
        {
            "Dashboard" => FormatDashboard(_state),
            "Incident Log" => FormatIncidents(_state),
            "Approval Queue" => "Approval queue will show actions that require admin authorization. Ban/kick approval plumbing can be expanded here.",
            "Player Lookup" => "Player lookup will show active AutoMod scopes, punishments, false positives, and adjustments for a selected player.",
            "Rules" => FormatRules(_state),
            "Tester" => "Enter text below and run the tester. Testing never creates incidents, notes, bans, or Discord logs.",
            "Discord Logs" => _state == null ? "No state." : $"Discord enabled: {_state.DiscordEnabled}\nDiscord logging is async and should never block chat.",
            "Sync / Health" => _state == null ? "No state." : $"NullLink enabled: {_state.NullLinkEnabled}\nNullLink healthy: {_state.NullLinkHealthy}\nUnsynced incidents: {_state.UnsyncedIncidents}\nRule store: {_state.RuleStorePath}",
            "Settings" => "Global AutoMod settings are CVar-backed. Rule behaviour is edited in the Rules tab and saved in-game.",
            _ => "Unknown tab."
        };

        if (tab == "Rules")
            LoadFirstRuleIntoEditor(_state);
    }

    public void ShowTestResult(AutoModTestResult result)
    {
        MainTitle.Text = "Tester Result";
        TesterControls.Visible = true;
        RuleEditorControls.Visible = false;
        MainText.Text =
            $"Matched: {result.Matched}\n" +
            $"Rule: {result.RuleId}\n" +
            $"Action: {result.ActionSummary}\n" +
            $"Cancel speech: {result.CancelSpeech}\n" +
            $"Approval: {result.RequiresApproval}\n" +
            $"Discord: {result.WouldDiscordLog}\n" +
            $"Points: {result.PointsBefore} -> {result.PointsAfter}\n" +
            $"Normalized: {result.NormalizedText}\n" +
            $"Feedback: {result.PlayerFeedback}\n" +
            $"Evidence: {result.EvidencePreview}";
    }

    public void ShowOperationResult(AutoModOperationResultMessage result)
    {
        MainTitle.Text = result.Success ? "AutoMod operation succeeded" : "AutoMod operation failed";
        MainText.Text = result.Message;
    }

    private void SelectTab(string tab)
    {
        TabSelected?.Invoke(tab);
        ShowTab(tab, _state);
    }

    private void ShowDashboard(AutoModUiState state)
    {
        ShowTab("Dashboard", state);
    }

    private static string FormatDashboard(AutoModUiState? state)
    {
        if (state == null)
            return "No AutoMod state yet.";

        return
            $"Recent incidents: {state.RecentIncidents.Count}\n" +
            $"Saved rules: {state.Rules.Count}\n" +
            $"Pending approvals: {state.PendingApprovals}\n" +
            $"Discord: {(state.DiscordEnabled ? "Enabled" : "Disabled")}\n" +
            $"Rule store: {state.RuleStorePath}\n\n" +
            "Use Rules to create/edit runtime rules. No YAML or prototypes are used.";
    }

    private static string FormatIncidents(AutoModUiState? state)
    {
        if (state == null || state.RecentIncidents.Count == 0)
            return "No incidents.";

        return string.Join('\n', state.RecentIncidents.Take(100).Select(x =>
            $"{x.CreatedAtUtc:u} | {x.PlayerNameAtTime} | {x.Channel} | {x.RuleId} | {x.ActionTaken} | {x.Status}"));
    }

    private static string FormatRules(AutoModUiState? state)
    {
        if (state == null || state.Rules.Count == 0)
            return "No runtime rules. Use Create Rule to create a disabled draft, edit JSON, then save and enable it.";

        return string.Join('\n', state.Rules.Select(x =>
            $"{(x.Enabled ? "ON " : "OFF")} | {x.Priority,4} | {x.Id} | {x.Name} | {x.Category} | {x.Severity} | {x.MatchKind} | {x.ActionSummary}"));
    }

    private void LoadFirstRuleIntoEditor(AutoModUiState? state)
    {
        if (state == null || state.EditableRules.Count == 0)
        {
            SelectedRuleId.Text = string.Empty;
            SetText(RuleJsonEditor, string.Empty);
            return;
        }

        var rule = state.EditableRules[0];
        SelectedRuleId.Text = rule.ID;
        SetText(RuleJsonEditor, AutoModRuleJsonFormatter.ToJson(rule));
    }

    private static string GetText(TextEdit edit)
    {
        return edit.TextLength == 0
            ? string.Empty
            : Rope.CollapseSubstring(edit.TextRope, 0..edit.TextLength);
    }

    private static void SetText(TextEdit edit, string text)
    {
        edit.TextRope = string.IsNullOrEmpty(text)
            ? Rope.Leaf.Empty
            : new Rope.Leaf(text);
    }
}
