# Rotes (prepared spells) and Tarot cards. Chains are glyph ids in weaving order.
ROTES = [
    ('RoteSpark', 'Spark', 'A quick bolt of heat.', ['FormBolt', 'EffectScorch']),
    ('RoteIgnite', 'Ignite', 'Sets what you touch alight, hard.', ['FormTouch', 'EffectFlame', 'AugmentAmplify']),
    ('RoteFrostBolt', 'Frost Bolt', 'A bolt of biting cold.', ['FormBolt', 'EffectChill']),
    ('RoteShockGrasp', 'Shocking Grasp', 'Lightning through your fingertips.', ['FormTouch', 'EffectShock', 'AugmentAmplify']),
    ('RoteMendingTouch', 'Mending Touch', 'Closes wounds with a touch.', ['FormTouch', 'EffectMend']),
    ('RoteHealingBloom', 'Healing Bloom', 'A soft burst that heals everyone close.', ['FormBurst', 'EffectWideMend']),
    ('RoteSmokeScreen', 'Smoke Screen', 'A cloud of smoke around you.', ['FormBurst', 'EffectSmoke']),
    ('RoteSmokeBolt', 'Smoke Bolt', 'Throws a bolt that bursts into smoke where it lands.', ['FormBolt', 'EffectSmoke']),
    ('RoteForceDoor', 'Force Door', 'Raises a wall of force where you point.', ['FormAimed', 'EffectForceWall']),
    ('RoteShockwave', 'Shockwave', 'Throws everything near you away.', ['FormBurst', 'EffectShove']),
    ('RoteGrasp', 'Grasping Hand', 'Drags everything near the point toward it.', ['FormAimed', 'EffectPull']),
    ('RoteThunderclap', 'Thunderclap', 'A wide crack that stuns everything around you.', ['FormNova', 'EffectStatic']),
    ('RoteBlinkLance', 'Passage Lance', 'Fire a lance. You arrive where it lands.', ['FormLance', 'EffectStep']),
    ('RoteSwapPlaces', 'Swap Places', 'Trade places with someone near the point.', ['FormAimed', 'EffectFold']),
    ('RoteFrostTrap', 'Frost Trap', 'A rune that freezes and trips whoever steps on it.', ['FormRune', 'EffectFrostbite']),
    ('RoteBlastTrap', 'Blast Trap', 'A rune that explodes when stepped on.', ['FormRune', 'EffectBlast']),
    ('RoteSiphon', 'Siphon', 'Drains life with a touch.', ['FormTouch', 'EffectDrain']),
    ('RoteWindThief', 'Wind Thief', 'Steals Wind from a caster you touch.', ['FormTouch', 'EffectSiphonWind']),
    ('RoteCarpCall', 'Carp Call', 'Summons carp where you point.', ['FormAimed', 'EffectMagicarp']),
    ('RoteFireNova', 'Fire Nova', 'A ring of fire around you.', ['FormNova', 'EffectInferno']),
    ('RoteArcLightning', 'Arc Lightning', 'A bolt of lightning that jumps between enemies.', ['FormBolt', 'EffectShock', 'AugmentChain', 'AugmentChain']),
    ('RoteScatterFlame', 'Scatter Flame', 'Three bolts of flame in a fan.', ['FormBolt', 'AugmentFork', 'EffectFlame']),
    ('RoteWardWall', 'Ward', 'A wall of force right where you stand.', ['FormSelf', 'EffectForceWall']),
    ('RoteFirebolt', 'Firebolt', 'The classic fast bolt of fire.', ['FormAimed', 'EffectFirebolt']),
    ('RoteFireball', 'Fireball', 'The classic explosive ball of fire.', ['FormAimed', 'EffectFireball']),
    ('RoteIceStorm', 'Ice Storm', 'A volley of ice spikes.', ['FormAimed', 'EffectIceStorm']),
    ('RoteBlink', 'Blink', 'Step to the point you choose.', ['FormAimed', 'EffectBlink']),
    ('RoteKnock', 'Knock', 'Open every door and locker near you.', ['FormSelf', 'EffectKnock']),
    ('RoteRepulse', 'Repulse', 'A shockwave that pushes everything away.', ['FormSelf', 'EffectRepulse']),
    ('RoteLightOrb', 'Lantern', 'A light to carry.', ['FormSelf', 'EffectWisp']),
]

# numeral, name, flavor, upright chain, reversed chain
TAROT = [
    ('0', 'The Fool', 'A step into nothing.', ['FormLance', 'EffectStep'], ['FormAimed', 'EffectFold']),
    ('I', 'The Magician', 'As above, so below.', ['FormBolt', 'EffectScorch', 'AugmentAmplify'], ['FormBolt', 'EffectChill', 'AugmentAmplify']),
    ('II', 'The High Priestess', 'What is hidden gives.', ['FormSelf', 'EffectWisp', 'EffectMend'], ['FormTouch', 'EffectSiphonWind']),
    ('III', 'The Empress', 'Abundance, or smothering.', ['FormBurst', 'EffectWideMend'], ['FormBurst', 'EffectVenom']),
    ('IV', 'The Emperor', 'Order, held by force.', ['FormAimed', 'EffectForceWall'], ['FormAimed', 'EffectImpact']),
    ('V', 'The Hierophant', 'Tradition mends. Or binds.', ['FormTouch', 'EffectMend', 'AugmentAmplify'], ['FormTouch', 'EffectDecay']),
    ('VI', 'The Lovers', 'A choice, and its cost.', ['FormTouch', 'EffectReplenish'], ['FormTouch', 'EffectDrain']),
    ('VII', 'The Chariot', 'Will, driven forward.', ['FormLance', 'EffectImpact'], ['FormOrb', 'EffectShove']),
    ('VIII', 'Strength', 'Gentle, and enormous.', ['FormSelf', 'EffectMend', 'AugmentAmplify'], ['FormBurst', 'EffectImpact']),
    ('IX', 'The Hermit', 'Apart, and watching.', ['FormSelf', 'EffectSmoke'], ['FormAimed', 'EffectSmoke', 'AugmentLinger']),
    ('X', 'Wheel of Fortune', 'Everything turns.', ['FormBurst', 'EffectStatic'], ['FormNova', 'EffectShove']),
    ('XI', 'Justice', 'Weighed and measured.', ['FormBolt', 'EffectShock'], ['FormBolt', 'EffectStormcall']),
    ('XII', 'The Hanged Man', 'Suspended, and seeing.', ['FormAimed', 'EffectStatic'], ['FormTouch', 'EffectStatic', 'AugmentAmplify']),
    ('XIII', 'Death', 'An ending is a door.', ['FormTouch', 'EffectDecay', 'AugmentAmplify'], ['FormNova', 'EffectDecay']),
    ('XIV', 'Temperance', 'Mix, and wait.', ['FormBurst', 'EffectRenew'], ['FormBurst', 'EffectMend']),
    ('XV', 'The Devil', 'Chains you chose.', ['FormRune', 'EffectInferno'], ['FormBolt', 'EffectInferno']),
    ('XVI', 'The Tower', 'Struck, and falling.', ['FormBolt', 'EffectBlast'], ['FormOrb', 'EffectBlast']),
    ('XVII', 'The Star', 'Hope, poured out.', ['FormBurst', 'EffectMend', 'EffectRenew'], ['FormAimed', 'EffectFlashRune']),
    ('XVIII', 'The Moon', 'Illusion and tide.', ['FormNova', 'EffectSmoke'], ['FormAimed', 'EffectMagicarp']),
    ('XIX', 'The Sun', 'Everything is lit.', ['FormNova', 'EffectScorch'], ['FormBurst', 'EffectFlame']),
    ('XX', 'Judgement', 'A call you cannot refuse.', ['FormNova', 'EffectStormcall'], ['FormBurst', 'EffectFrostbite']),
    ('XXI', 'The World', 'Complete, and begun again.', ['FormAimed', 'EffectFold', 'AugmentEcho'], ['FormLance', 'EffectStep', 'AugmentDelay']),
]
