import sys, os, hashlib, itertools, re, json
sys.path.insert(0, '/home/claude/tools')
from glyphdata import *
from castdata import *
from PIL import Image, ImageDraw, ImageFilter

ROOT = sys.argv[1]
YML = ROOT + '/Resources/Prototypes/_Starlight/Wizard'
LOC = ROOT + '/Resources/Locale/en-US/_Starlight/wizard'
RSI = ROOT + '/Resources/Textures/_Starlight/Interface/Wizard/glyphs.rsi'
os.makedirs(YML + '/Glyphs', exist_ok=True); os.makedirs(YML + '/Casting', exist_ok=True); os.makedirs(RSI, exist_ok=True)

# ---------- sigils ----------
def adj(a, b):
    ra, ca = divmod(a, 3); rb, cb = divmod(b, 3)
    return a != b and max(abs(ra - rb), abs(ca - cb)) == 1
def paths(n):
    out = []
    def rec(p):
        if len(p) == n: out.append(tuple(p)); return
        for nx in range(9):
            if nx not in p and adj(p[-1], nx): rec(p + [nx])
    for s in range(9): rec([s])
    return out
pool = {}
for n in (4, 5):
    for p in paths(n):
        key = min(p, p[::-1]); pool[key] = True
pool = sorted(pool.keys())
all_ids = [g[0] for g in FORMS] + [g[0] for g in EFFECTS] + [g[0] for g in AUGMENTS]
sigils = {}; used = set()
for gid in sorted(all_ids):
    h = int(hashlib.md5(gid.encode()).hexdigest(), 16)
    i = h % len(pool)
    while pool[i] in used: i = (i + 1) % len(pool)
    used.add(pool[i]); sigils[gid] = pool[i]

# ---------- icons ----------
def col(h): h = h.lstrip('#'); return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
S = 4; SZ = 48
def icon(gid, accent, shape):
    im = Image.new('RGBA', (SZ * S, SZ * S), (0, 0, 0, 0)); d = ImageDraw.Draw(im)
    ac = col(accent)
    d.rounded_rectangle((2*S, 2*S, (SZ-2)*S, (SZ-2)*S), radius=7*S, fill=(20, 14, 36, 245), outline=ac + (255,), width=2*S)
    d.rounded_rectangle((5*S, 5*S, (SZ-5)*S, (SZ-5)*S), radius=5*S, outline=tuple(int(c*0.45) for c in ac) + (255,), width=1*S)
    pts = []
    for k in sigils[gid]:
        r, c = divmod(k, 3); pts.append(((14 + c * 10) * S, (14 + r * 10) * S))
    glow = Image.new('RGBA', im.size, (0, 0, 0, 0)); gd = ImageDraw.Draw(glow)
    gd.line(pts, fill=ac + (200,), width=5*S, joint='curve')
    glow = glow.filter(ImageFilter.GaussianBlur(3*S)); im = Image.alpha_composite(im, glow); d = ImageDraw.Draw(im)
    for r in range(3):
        for c in range(3):
            x, y = (14 + c * 10) * S, (14 + r * 10) * S
            d.ellipse((x-1.2*S, y-1.2*S, x+1.2*S, y+1.2*S), fill=tuple(int(v*0.5) for v in ac) + (255,))
    d.line(pts, fill=(245, 240, 255, 255), width=int(2.2*S), joint='curve')
    sx, sy = pts[0]; d.ellipse((sx-2.4*S, sy-2.4*S, sx+2.4*S, sy+2.4*S), fill=ac + (255,))
    # category pip
    if shape == 'Form': d.polygon([(SZ*S-9*S, 6*S), (SZ*S-5*S, 10*S), (SZ*S-9*S, 14*S), (SZ*S-13*S, 10*S)], fill=ac + (255,))
    if shape == 'Augment': d.ellipse((SZ*S-13*S, 6*S, SZ*S-6*S, 13*S), outline=ac + (255,), width=2*S)
    return im.resize((SZ, SZ), Image.LANCZOS)
states = []
def accent_for(kind, schools):
    if kind == 'Form': return FORM_COLOR
    if kind == 'Augment': return AUG_COLOR
    return SCHOOLS[schools[0]]
for g in FORMS: icon(g[0], FORM_COLOR, 'Form').save(f'{RSI}/{g[0]}.png'); states.append(g[0])
for g in AUGMENTS: icon(g[0], AUG_COLOR, 'Augment').save(f'{RSI}/{g[0]}.png'); states.append(g[0])
for g in EFFECTS: icon(g[0], SCHOOLS[g[4][0]], 'Effect').save(f'{RSI}/{g[0]}.png'); states.append(g[0])
json.dump({"version": 1, "license": "CC0-1.0", "copyright": "Generated for the Starlight wizard rework.", "size": {"x": SZ, "y": SZ}, "states": [{"name": s} for s in states]}, open(RSI + '/meta.json', 'w'), indent=2)

# ---------- yaml ----------
def y(v, ind):
    pad = '  ' * ind
    if isinstance(v, dict):
        out = []
        for k, val in v.items():
            if isinstance(val, dict): out.append(f'{pad}{k}:'); out.append(y(val, ind + 1))
            else: out.append(f'{pad}{k}: {sc(val)}')
        return '\n'.join(out)
def sc(v):
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, list): return '[ ' + ', '.join(str(x) for x in v) + ' ]'
    return str(v)
def loc(gid, what): return f'glyph-{gid.lower()}-{what}'
icon_line = lambda gid: f'  icon: {{ sprite: _Starlight/Interface/Wizard/glyphs.rsi, state: {gid} }}'
def head(gid, cat, cost, schools=None):
    s = [f'- type: spellGlyph', f'  id: {gid}', f'  category: {cat}', f'  name: {loc(gid,"name")}', f'  description: {loc(gid,"desc")}', f'  cost: {cost}']
    if schools: s.append(f'  schools: [ {", ".join(schools)} ]')
    s.append(f'  sigil: "{"-".join(map(str, sigils[gid]))}"'); s.append(icon_line(gid)); return s

out = ['# GENERATED by tools/gen_glyphs.py. Edit tools/glyphdata.py, not this file.', '']
for gid, name, desc, cost, deliv, ex in FORMS:
    s = head(gid, 'Form', cost); s.append(f'  delivery: {deliv}')
    for k, v in ex.items(): s.append(f'  {k}: {v}')
    out += s + ['']
open(YML + '/Glyphs/forms.yml', 'w').write('\n'.join(out))

out = ['# GENERATED by tools/gen_glyphs.py. Edit tools/glyphdata.py, not this file.', '']
for gid, name, desc, cost, kind, val in AUGMENTS:
    s = head(gid, 'Augment', cost); s.append(f'  augment: {kind}'); s.append(f'  value: {val}')
    out += s + ['']
open(YML + '/Glyphs/augments.yml', 'w').write('\n'.join(out))

out = ['# GENERATED by tools/gen_glyphs.py. Edit tools/glyphdata.py, not this file.', '']
for gid, name, desc, cost, schools, kind, payload in EFFECTS:
    s = head(gid, 'Effect', cost, schools)
    if kind == 'u':
        s.append('  effects:')
        for t, fields in payload:
            s.append(f'  - !type:{t}GlyphEffect')
            for k, v in fields.items():
                if isinstance(v, dict): s.append(f'    {k}:'); s.append(y(v, 3))
                else: s.append(f'    {k}: {sc(v)}')
    elif kind == 'w': s.append(f'  worldEvent: {payload}')
    else: s.append(f'  instantEvent: {payload}')
    out += s + ['']
open(YML + '/Glyphs/effects.yml', 'w').write('\n'.join(out))

# ---------- rotes / tarot (+ validation that mirrors the compiler) ----------
meta = {g[0]: ('Form', dict(deliv=g[4], extra=g[5])) for g in FORMS}
meta.update({g[0]: ('Augment', dict(kind=g[4], value=g[5])) for g in AUGMENTS})
for g in EFFECTS: meta[g[0]] = ('Effect', dict(kind=g[5], schools=g[4]))
def validate(name, chain):
    forms = [c for c in chain if meta[c][0] == 'Form']
    assert len(forms) == 1 and meta[chain[0]][0] == 'Form', f'{name}: needs exactly one Form first'
    deliv = meta[forms[0]][1]['deliv']; effs = [c for c in chain if meta[c][0] == 'Effect']
    assert 1 <= len(effs) <= 4, f'{name}: effect count'
    for e in effs:
        kind = meta[e][1]['kind']
        ok = kind == 'u' or (kind == 'w' and deliv == 'Aimed') or (kind == 'i' and deliv in ('Self', 'Burst'))
        assert ok, f'{name}: {e} incompatible with {deliv}'
    for a in [c for c in chain if meta[c][0] == 'Augment']:
        if meta[a][1]['kind'] == 'Split': assert deliv == 'Bolt', f'{name}: split needs bolt'
    assert len(chain) <= 8, f'{name}: too long'
out = ['# GENERATED by tools/gen_glyphs.py. Edit tools/castdata.py, not this file.', '']
for rid, nm, desc, chain in ROTES:
    validate(rid, chain)
    out += ['- type: roteSpell', f'  id: {rid}', f'  name: rote-{rid.lower()}-name', f'  description: rote-{rid.lower()}-desc', f'  chain: [ {", ".join(chain)} ]', '']
open(YML + '/Casting/rotes.yml', 'w').write('\n'.join(out))
STATES = {'The Fool':'the_fool','The Magician':'the_magician','The High Priestess':'the_high_priestess','The Empress':'the_empress','The Emperor':'the_emperor','The Hierophant':'the_hierophant','The Lovers':'the_lovers','The Chariot':'the_chariot','Strength':'strength','The Hermit':'the_hermit','Wheel of Fortune':'the_wheel_of_fortune','Justice':'justice','The Hanged Man':'the_hanged_man','Death':'death','Temperance':'temperance','The Devil':'the_devil','The Tower':'the_tower','The Star':'the_star','The Moon':'the_moon','The Sun':'the_sun','Judgement':'judgement','The World':'the_world'}
out = ['# GENERATED by tools/gen_glyphs.py. Edit tools/castdata.py, not this file.', '']
cards = ['# GENERATED by tools/gen_glyphs.py. Edit tools/castdata.py, not this file.', '']
for i, (num, nm, flavor, up, rev) in enumerate(TAROT):
    validate(nm + ' up', up); validate(nm + ' rev', rev)
    tid = 'Tarot' + re.sub(r'[^A-Za-z]', '', nm)
    out += ['- type: tarotCard', f'  id: {tid}', f'  numeral: "{num}"', f'  name: tarot-{tid.lower()}-name', f'  flavor: tarot-{tid.lower()}-flavor', f'  entity: TarotSpellCard{tid[5:]}', f'  upright: [ {", ".join(up)} ]', f'  reversed: [ {", ".join(rev)} ]', '']
    cards += ['- type: entity', '  parent: TarotSpellCardBase', f'  id: TarotSpellCard{tid[5:]}', f'  name: {nm}', f'  description: {flavor}', '  components:', '  - type: Sprite', '    sprite: _Moffstation/Objects/Misc/Cards/card_tarot.rsi', f'    state: {STATES[nm]}', '']
open(YML + '/Casting/tarot.yml', 'w').write('\n'.join(out))
open(YML + '/Casting/tarot_cards.yml', 'w').write('\n'.join(cards))

# ---------- locale ----------
lines = ['# GENERATED by tools/gen_glyphs.py.', '']
for g in FORMS: lines += [f'{loc(g[0],"name")} = {g[1]}', f'{loc(g[0],"desc")} = {g[2]}']
for g in AUGMENTS: lines += [f'{loc(g[0],"name")} = {g[1]}', f'{loc(g[0],"desc")} = {g[2]}']
for g in EFFECTS: lines += [f'{loc(g[0],"name")} = {g[1]}', f'{loc(g[0],"desc")} = {g[2]}']
lines.append('')
for rid, nm, desc, chain in ROTES: lines += [f'rote-{rid.lower()}-name = {nm}', f'rote-{rid.lower()}-desc = {desc}']
lines.append('')
for num, nm, flavor, up, rev in TAROT:
    tid = 'Tarot' + re.sub(r'[^A-Za-z]', '', nm)
    lines += [f'tarot-{tid.lower()}-name = {nm}', f'tarot-{tid.lower()}-flavor = {flavor}']
open(LOC + '/glyphs.ftl', 'w').write('\n'.join(lines) + '\n')
print('glyphs', len(all_ids), 'rotes', len(ROTES), 'tarot', len(TAROT), 'sigils unique', len(used))
