using Content.Shared._Starlight.CartridgeLoader.Cartridges;
using Content.Shared._Starlight.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEntry : BoxContainer
{
    public event Action<uint>? OnPressed;
    private uint _number;
    private Action<EventArgs>? _pressHandler;

    public NanoChatEntry() =>
        RobustXamlLoader.Load(this);

    public void SetRecipient(NanoChatRecipient recipient, uint number, bool isSelected)
    {
        // Remove old handler if it exists
        if (_pressHandler != null)
            ChatButton.OnPressed -= _pressHandler;

        _number = number;

        // Create and store new handler
        _pressHandler = _ => OnPressed?.Invoke(_number);
        ChatButton.OnPressed += _pressHandler;

        // "Unknown" fallback for name, was having weird issues when implementing group chats.
        NameLabel.Text = SharedNanoChatSystem.Truncate(recipient.Name ?? "Unknown", SharedNanoChatSystem.MaxFullNameLength);
        JobLabel.Text = SharedNanoChatSystem.Truncate(recipient.JobTitle ?? "", SharedNanoChatSystem.MaxJobTitleLength);
        JobLabel.Visible = !string.IsNullOrEmpty(recipient.JobTitle);
        UnreadIndicator.Visible = recipient.HasUnread;

        // Show group icon for group chats
        GroupIcon.Visible = recipient.IsGroup;

        ChatButton.ModulateSelfOverride = isSelected ? NanoChatMessageBubble.OwnMessageColor : null;
    }
}
